(function () {
  const ID = "csesbm-review-root", WIDTH = "csesbm:reviewPanelWidth", OPEN = "csesbm:reviewPanelOpen";
  const el = (tag, cls, text) => { const n = document.createElement(tag); if (cls) n.className = cls; if (text != null) n.textContent = text; return n; };
  function root() { let n = document.getElementById(ID); if (!n) { n = el("aside", "csesbm-review"); n.id = ID; n.setAttribute("aria-label", "CSES submission review"); document.body.append(n); } return n; }
  function width(n) { const w = Math.max(380, Math.min(900, Number(localStorage.getItem(WIDTH)) || 560)); n.style.setProperty("--panel-width", w + "px"); }
  function close(opts) { localStorage.setItem(OPEN, "false"); if (opts && opts.onClose) opts.onClose(); const n = document.getElementById(ID); if (n) n.remove(); }
  function header(title, status, opts) { const h = el("header", "csesbm-rv-header"); h.append(el("span", "csesbm-rv-status", status)); h.append(el("h2", "csesbm-rv-title", title)); const x = el("button", "csesbm-rv-close", "×"); x.type = "button"; x.setAttribute("aria-label", "Close review"); x.onclick = () => close(opts); h.append(x); return h; }
  function section(title, children) { const s = el("section", "csesbm-rv-section"); s.append(el("h3", "csesbm-rv-h", title)); (Array.isArray(children) ? children : [children]).filter(Boolean).forEach((x) => s.append(x)); return s; }
  function list(items, numbered) { const u = el(numbered ? "ol" : "ul", "csesbm-rv-list"); (items || []).forEach((item) => u.append(el("li", null, item))); return u; }
  function complexity(c) { const d = el("div", "csesbm-rv-complexity"); d.append(el("span", "csesbm-rv-badge", "Time " + (c && c.time || "—")), el("span", "csesbm-rv-badge", "Space " + (c && c.space || "—"))); return d; }
  function resize(n) { const grip = el("div", "csesbm-rv-resize"); grip.onpointerdown = (e) => { const start = e.clientX, old = n.getBoundingClientRect().width; grip.setPointerCapture(e.pointerId); const move = (m) => { const w = Math.max(380, Math.min(900, old + (start - m.clientX))); n.style.setProperty("--panel-width", w + "px"); }; const up = () => { localStorage.setItem(WIDTH, String(Math.round(n.getBoundingClientRect().width))); grip.removeEventListener("pointermove", move); grip.removeEventListener("pointerup", up); }; grip.addEventListener("pointermove", move); grip.addEventListener("pointerup", up); }; n.append(grip); }
  function loading(stage, opts) { const n = root(); n.innerHTML = ""; width(n); localStorage.setItem(OPEN, "true"); n.append(header("Submission review", "Working", opts), el("div", "csesbm-rv-progress", stage), el("div", "csesbm-rv-loading", "Please keep this tab open.")); resize(n); }
  function approach(a, i) { const d = el("details", "csesbm-rv-approach"); d.open = i === 0; const sum = el("summary", null); sum.append(el("strong", null, (i + 1) + ". " + a.name), el("span", "csesbm-rv-badge", a.time_complexity + " · " + a.space_complexity)); d.append(sum, el("p", "csesbm-rv-copy", a.idea), section("Logic", list(a.steps, true)), section("Why it works", el("p", "csesbm-rv-copy", a.correctness)), section("Trade-offs", el("p", "csesbm-rv-copy", a.tradeoffs)));
    const bar = el("div", "csesbm-rv-code-bar"); const copy = el("button", "csesbm-rv-copy-btn", "Copy code"); copy.onclick = async () => { try { await navigator.clipboard.writeText(a.code); copy.textContent = "Copied"; setTimeout(() => copy.textContent = "Copy code", 1000); } catch (_) { copy.textContent = "Copy failed"; } }; bar.append(el("span", null, "Complete code"), copy); const pre = el("pre", "csesbm-rv-code"); pre.textContent = a.code; d.append(bar, pre); return d; }
  function render(summary, submission, opts) { const n = root(); n.innerHTML = ""; width(n); localStorage.setItem(OPEN, "true"); const accepted = Boolean(submission && submission.accepted); n.className = "csesbm-review " + (accepted ? "is-accepted" : "is-rejected"); n.append(header(summary.diagnosis || submission.verdict || "Quick review", "Quick review ready", opts)); const body = el("div", "csesbm-rv-body"); body.append(section("Diagnosis", el("p", "csesbm-rv-copy", summary.diagnosis)), section("Evidence", list(summary.evidence)), section("Complexity", complexity(summary.complexity)), section(accepted ? "Improvement direction" : "First hint", el("p", "csesbm-rv-hint", summary.first_hint))); if (summary.code_quality && summary.code_quality.length) body.append(section("Code quality", list(summary.code_quality))); const detailSlot = el("div", "csesbm-rv-detail-slot"); body.append(detailSlot); n.append(body); resize(n); if (opts.detailLoading) detailSlot.append(el("div", "csesbm-rv-progress", accepted ? "Generating approaches…" : "Generating deeper hints…")); if (opts.detail) renderDetail(detailSlot, opts.detail, accepted, opts); else if (opts.detailError) { const retry = el("button", "csesbm-rv-retry", "Retry details"); retry.onclick = opts.onRetryDetail; detailSlot.append(section("Details unavailable", [el("p", "csesbm-rv-error", opts.detailError), retry])); } }
  function renderDetail(slot, detail, accepted, opts) { slot.innerHTML = ""; if (accepted) { const s = section("Approaches", (detail.approaches || []).map(approach)); slot.append(s); if (detail.improvements && detail.improvements.length) slot.append(section("Improvements", list(detail.improvements))); } else { slot.append(section("Deeper critique", list(detail.critique)), section("Layered hints", list(detail.hints, true))); } }
  function error(message, opts) { const n = root(); n.innerHTML = ""; width(n); n.append(header("Could not start review", "Error", opts), el("div", "csesbm-rv-error", message)); resize(n); }
  globalThis.CSESReviewPanel = { renderLoading: loading, renderSummary: render, renderError: error };
})();
